name: Serkan Binyar
favicon: null
layout_spectrum: 0.84057
typography_spectrum: 0.015137827722355723
title: Serkan Binyar
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.7780640991404653
  rhythmicContrast: 0.5
purpose: []
